# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: simwai.babae
PackageVersion: 0.1.0
InstallerType: portable
InstallModes:
- silent
- silentWithProgress
Commands:
- babae
Installers:
- Architecture: x64
  InstallerUrl: https://gitlab.com/api/v4/projects/simwai%2Fbabae/packages/generic/babae/0.1.0/babae-0.1.0.zip
  InstallerSha256: 90152CEE3536CEA344946EF1058A9B27B9BD08729D935253C74EE035D1F76894
ManifestType: installer
ManifestVersion: 1.12.0
